version: "3"
services:
  wp-db:
    image: "postgres"
    container_name: "wp2024_labs"
    environment:
      - POSTGRES_USER=wp
      - POSTGRES_PASSWORD=wp123
      - POSTGRES_DB=labs
    ports:
      - "2526:2526"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data